project:
  type: book

book:
  title: "C++ para Principiantes"
  author: "Alex Dannis Lipa Quispe"
  date: "2025-05-29"

  chapters:
    # - portada.qmd         Portada con imagen a página completa
    - index.qmd          # Introducción al libro
    - capitulo1.qmd
    - capitulo2.qmd
    - capitulo3.qmd
    - capitulo4.qmd
    - capitulo5.qmd
    - capitulo6.qmd
    - capitulo7.qmd
    - capitulo8.qmd
    - capitulo9.qmd
    - capitulo10.qmd
    - capitulo11.qmd
    - capitulo12.qmd
    - capitulo13.qmd
    - capitulo14.qmd
format:
  pdf:
    pdf-engine: xelatex
    papersize: a4
    fontsize: 11pt
    linestretch: 1.3

    margin-left: 2cm
    margin-right: 2cm
    margin-top: 2cm
    margin-bottom: 2cm

    code-block-bg: true
    code-block-border-left: "#3C3C3C"
    code-block-font-size: 90%

    include-in-header: preambulo.tex