---
title: "Entradas y Salidas"
author: "Alex Dannis Lipa Quispe"
---

## Inicio:

Para empezar a escribir un código en C++ necesitas tener un lugar compilador o un lugar donde escribir código, eso te lo dejo a tu elección.

Primeramente, cada programa se inicia con:

``` cpp
#include <iostream>
```

La palabra **#include \<iostream\>** incluye la librería para poder hacer la entrada y salida de valores, los cuales son:

``` cpp
cin >> //esto se utiliza para entrar o digitar valores a tu programa.
cout << //esto se utiliza para mostrar mensaje en tu programa.
```

La estructura principal es de esta manera:

``` cpp
#include <iostream>
int main(){  //Esta es la función principal que leerá el programa
  
    return 0; //Si el programa funciona bien retornara 0
}
```

## Salidas:

Para mostrar tu primer `hola mundo` en c++ se hace de la siguiente manera:

``` cpp
#include <iostream>
int main(){
    std::cout << "Hola mundo"<< std::endl;
    return 0;
}
```

Este fragmento de código imprimirá tu primer "Hola mundo". Recuerda que para enviar un mensaje es importante que esté entre comillas dobles **""**, y si solo va a tener un carácter debe estar entre comillas simples **''**.

Para simplificar el código, si te resulta estresante, puedes usar **using namespace std**. Esto, de manera simple, permite abreviar u omitir el **std::**. El código quedará de la siguiente manera:

``` cpp
#include <iostream>
int main(){
    std::cout << "Hola mundo"<<std::endl;
    return 0;
}/* cabe recalcar que para proyectos grandes el "using namespace std" 
ara tu programa menos optimo */
```

Los mensajes que pongo en los códigos no se leen porque son comentarios. Si deseas poner un comentario lineal, usa **//** y para comentarios multilínea debes usar **/** ... **/** escribiendo el mensaje dentro de los asteriscos.

## Entradas:

Para guardar y mostrar valores, para compilar el código hacemos esto:

``` cpp
#include <iostream>
int main(){
    int valor;
    std::cout << "Digite un valor: "; 
    std:: cin >> valor;
    std::cout << "El valor es: "<<valor<<std::endl;
    return 0;
}
```

Este código lo que hace es declarar una variable de nombre **valor** de tipo entero (int) con el mensaje "Digite un valor". Luego, en el programa, el usuario digitara un valor numérico que se almacenará en **valor**.

Para imprimir el valor introducido, se usa un `cout` seguido del nombre de la variable a mostrar. Cabe recalcar que si no se asigna un valor a la variable, se imprimirá un dato basura o un valor sin sentido.

```{=latex}
\begin{tcolorbox}[custombox]
Digite un valor: 15\\
El valor es: 15
\end{tcolorbox}
```

Para hacer operaciones se hace de la siguiente manera:

``` cpp
#include <iostream>
int main(){
    int num1 = 8, num2 = 4, suma, multiplicacion;
    suma = num1 + num2;  //en este caso res será igual a 12.
    multiplicacion = num1 * num2;
    // el endl es como un salto de linea.
    atd::cout << suma <<" || "<< multiplicacion<<std::endl; 
    // tambien lo podemos poner de manera directa.
    std::cout << num1 - num2<<"  || "<< num1 / num2<<std::endl;
    return 0;
}
```

Hicimos las operaciones básicas que todos conocemos (+, -, \*, /). El fragmento de código se mostrará de la siguiente manera:

```{=latex}
\begin{tcolorbox}[custombox]
12 || 32\\
4  || 2
\end{tcolorbox}
```

Tienes que ser creativo para poder realizar cualquier tipo de operaciones aritméticas. Por ejemplo, realizaremos un ejercicio simple que es resolver esta ecuación: La fórmula es: $[ a \times \left( \frac{b}{c} \right) ]$

Empecemos.

``` cpp
#include <iostream>
int main(){
    float a,b,c, resultado;
    std::cout<<"Digite 3 numeros separados por espacios o saltos de linea: ";
    std::cin>>a>>b>>c;
    //En este caso primero se ejecuta la divisón y luego la multiplicaión.
    resultado = a*(b/c); 
    std::cout << "El resultado es: "<<resultado<<std::endl;
    return 0;
}
```

Lo que hicimos es declarar 4 variables de tipo flotante para no perder los decimales del resultado. Ten en cuenta que **resultado** almacena el resultado y lo imprimimos como se muestra a continuación:

```{=latex}
\begin{tcolorbox}[custombox]
Digite 3 numeros separados por espacios o saltos de linea: 3 4 5 \\
El resultado es: 12
\end{tcolorbox}
```

Para finalizar es recomendable que tengas cuidado con las operaciones que agregues a tu programa.
